In [45]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits

digits = load_digits()

In [46]:
from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test = train_test_split(digits.data,digits.target,test_size = 0.3)

In [47]:
lr = LogisticRegression()
lr.fit(x_train,y_train)
lr.score(x_test,y_test)

c:\Users\snehs\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9574074074074074

In [48]:
svm = SVC()
svm.fit(x_train,y_train)
svm.score(x_test,y_test)

0.9888888888888889

In [49]:
rf = RandomForestClassifier()
rf.fit(x_train,y_train)
rf.score(x_test,y_test)

0.9592592592592593

In [54]:
from sklearn.model_selection import KFold
kf = KFold(n_splits = 8)
kf

KFold(n_splits=8, random_state=None, shuffle=False)

In [55]:
for train_index , test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)

[2 3 4 5 6 7 8] [0 1]
[0 1 3 4 5 6 7 8] [2]
[0 1 2 4 5 6 7 8] [3]
[0 1 2 3 5 6 7 8] [4]
[0 1 2 3 4 6 7 8] [5]
[0 1 2 3 4 5 7 8] [6]
[0 1 2 3 4 5 6 8] [7]
[0 1 2 3 4 5 6 7] [8]


In [56]:
def get_score(model,x_train,x_test,y_train,y_test):
    model.fit(x_train,y_train)
    return model.score(x_test,y_test)

In [57]:
get_score(LogisticRegression(),x_train,x_test,y_train,y_test)

c:\Users\snehs\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9574074074074074

In [58]:
get_score(SVC(),x_train,x_test,y_train,y_test)

0.9888888888888889

In [59]:
get_score(RandomForestClassifier(),x_train,x_test,y_train,y_test)

0.9740740740740741

In [60]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=5)

In [63]:
scores_lr = []
scores_svm = []
scores_rf = []

for train_index , test_index in kf.split(digits.data):
    x_train , x_test , y_train , y_test = digits.data[train_index],digits.data[test_index],digits.target[train_index],digits.target[test_index]
    
    scores_lr.append(get_score(LogisticRegression(),x_train,x_test,y_train,y_test))
    scores_svm.append(get_score(SVC(),x_train,x_test,y_train,y_test))
    scores_rf.append(get_score(RandomForestClassifier(),x_train,x_test,y_train,y_test))

c:\Users\snehs\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\snehs\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/st

In [64]:
scores_lr

[0.9066666666666666,
 0.9688888888888889,
 0.8933333333333333,
 0.9466666666666667,
 0.9688888888888889,
 0.9419642857142857,
 0.9241071428571429,
 0.9107142857142857]

In [65]:
scores_svm

[0.9555555555555556,
 0.9822222222222222,
 0.9555555555555556,
 0.9822222222222222,
 0.9866666666666667,
 0.9910714285714286,
 0.9821428571428571,
 0.9196428571428571]

In [66]:
scores_rf

[0.9244444444444444,
 0.9688888888888889,
 0.92,
 0.9377777777777778,
 0.9733333333333334,
 0.9732142857142857,
 0.9553571428571429,
 0.90625]

In [67]:
from sklearn.model_selection import cross_val_score

In [68]:
cross_val_score(LogisticRegression(),digits.data,digits.target)

c:\Users\snehs\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\snehs\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/st

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [69]:
cross_val_score(SVC(),digits.data,digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [70]:
cross_val_score(RandomForestClassifier(),digits.data,digits.target)

array([0.92777778, 0.92222222, 0.96100279, 0.95543175, 0.92200557])